version: "3.8"

services:
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/:/etc/prometheus/
    networks:
      - fullstack
  # grafana:
  #   image: grafana/grafana-oss:latest
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
  #   depends_on:
  #     - prometheus
  #   networks:
  #     - fullstack
  # go:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   env_file:
  #     - .env # golang env
  #   ports:
  #     - "8081:8081"
  #   depends_on:
  #     - prometheus
  #     - grafana
  #   networks:
  #     - fullstack
networks:
  fullstack:
    driver: bridge
