version: "3.8"

services:
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - "/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml"
    networks:
      - fullstack
  go:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env # golang env
    ports:
      - "3000:8081"
    networks:
      - fullstack
networks:
  fullstack:
    driver: bridge
